### PR TITLE
Set up Docker For Server

### LINKED ISSUE #115: Set up Docker for Server
- [ ] Create Dockerfile to run server application
- [ ] Edit docker-compose.yml to include server
- [ ] Create mock data file for database

### PR DESCRIPTION
**Pull request by a-camarillo**
#### What is the purpose of your change?
- Set up Docker for webserver along with some mock data
- fixes #115 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
- Webserver Directory

#### What features/fixes are deferred/not handled in this PR?
-

## Checklist
- [ ] Adds unit tests
- [x] Has a work item linked to the PR

### CODE REVIEW

**Comment by a-camarillo** [comment]
@jwu910 I'm confused but if you feel like we need multiple, I don't see why that's an issue. Also not sure if webserver running with db will cause any issues, I will have to look into it further.

As we have the compose file set up right now I think it should be fine since it's essentially spinning up the backend stack to allow the frontend devs to test with it but if you think otherwise let me know.

**Comment by jwu910** [comment]
Just curious, would backend devs be spinning up with the compose file to work too? at least should be for the DB gut if you spin up the webserver container, are you still able to work in your local env in python?

**Comment by a-camarillo** [comment]
backend shouldn't *need* to spin up the compose file if we're working on just the webserver. The way I have been working is spinning up a postgres container and specifying the database engine uri in the .env file. The flask server then reads that uri and uses that to connect to the database.

**Comment by jwu910** [comment]
How do you spin up your database container then?

**Comment by a-camarillo** [comment]
If I don't have a postgres container I'm working with it's usually just a 
``` 
docker run --name "The name for the container" \
-e POSTGRES_USER="a username for the database" \
-e POSTGRES_PASSWORD="some password" \
-e POSTGRES_DB="some database name" \
-p 5432:5432 \
-d postgres
```
if the container is already created I just use `docker start "name of container or container id"`

**Comment by jwu910** [comment]
Doesn't the compose file handle this for the database?

**Comment by a-camarillo** [comment]
yes but the purpose of docker compose is to run a multi-container application and working on the webserver locally doesn't *need* this since everything should also be contained in the local virtual environment so working locally on the webserver you can use docker compose but it isn't a requirement.

**Comment by a-camarillo** [comment]
yah I think they will also have to make sure they have a few environment variables set in order for both the database container to start up and the flask server in the webserver container

**Comment by jwu910** [comment]
Agreed, can draft some docs to support anyone new to docker on how to spin that up locally for the BE devs and drop a note for the FE notes to spin that up as well? should be just something like `docker-compose up` right? Or do you think we should just have separate commands for each?

**Comment by a-camarillo** [comment]
If you feel like that would help then sure. Here are some example use cases of using multiple docker compose files. Also worth noting compose is moving to v2 so the command is now `docker compose up`.

**Comment by jwu910** [comment]
Cool, yeah whatever version we are using, just gotta document, if we bump to 2, let's make sure our configs and commands in the readme reflect that, and we should be fine, if you don't think you or lily need the compose right now we can move forward with the intent for it to provide data for Frontend devs

**Review by jwu910 — APPROVED** [review]
After discussion, these changes look fine, i think lets just double check the docs to make sure the readme is updated and accurately reflecting the commands that need to be run. If we need a separate mention for backend devs to spin up the DB but not the web server with docker, lets add that, too. then we can get this merged

**Comment by a-camarillo** [comment]
@jwu910 I edited the READMEs to reflect the changes, should be good to merge now

**Pull request merged**
