### PR TITLE
ticket 30: added scraper code (needs additional work)

### LINKED ISSUE #30: Scraper build and find functions that can be used
Determine what functionality is reusable for the scraper to scrape from multiple sites. what technologies are you using for building the scraper?  What research is being done to get the data

### PR DESCRIPTION
**Pull request by lilyxmeng**
#### What is the purpose of your change?
Adding baseline code for the scraper. It lays out the foundation of what we should build upon, given a few bugs in the code that we need to fix (does not scrape, perhaps being blocked by the website or not getting the correct HTML blocks?).
Fixes #30 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
Modifies scraper/main.py.

#### What features/fixes are deferred/not handled in this PR?
It adds baseline code to get us started with the scraper, which means it does not work.

## Checklist
- [ ] Debug the code, ensure it scrapes the listed websites in the code

### CODE REVIEW

**Comment by michachan** [comment]
Looks good, just be sure to fix the lint issue.

**Review by michachan — APPROVED** [review]

**Comment by jwu910** [comment]
should be able to also just run `black .` (i think) from inside your venv

**Comment by lilyxmeng** [comment]
> @lilyxmeng you need any help with this?

Yes. I have exams every day this upcoming week so unfortunately, I won't have time to fix the issue until the following week.

**Comment by jwu910** [comment]
Gotcha, we'll reassign. Thanks!

**Comment by jwu910** [comment]
@a-camarillo can you take a look at this PR, pull it down and see if you can take a min to debug and get this ready for review and merge?

**Comment by a-camarillo** [comment]
@jwu910 sounds good, is the issue just the linting?

**Comment by jwu910** [comment]
No clue yet, I haven't checked this out, will have to verify things make sense and can support the issue and forward movement of the scraper side.

/cc: @lilyxmeng @DarrenLee09 @kpxwinter

**Comment by a-camarillo** [comment]
Ok, lets get some more detail on what's expected of this because I'm still working on the user management tickets

**Comment by jwu910** [comment]
@DarrenLee09 or @lilyxmeng if you have time, please help knowledge transfer for this

**Comment by jwu910** [comment]
@michachan you have details on the reason for closure on this? Will we close the corresponding ticket as well and create something new to target this work?

CC: @kpxwinter @victoriatran17

**Comment by jwu910** [comment]
Draft PRs are a thing!

**Pull request closed without merging**
